perl glossario.pl
pdflatex Glossario.tex
makeglossaries Glossario
pdflatex Glossario
del Glossario.aux
del Glossario.glo
del Glossario.glg
del Glossario.gls
del Glossario.ist
del Glossario.log
del Glossario.out
